baseURL: https://windfenn.co.uk/
languageCode: 'en-gb'
title: 'Wild Fenn'

## Site Settings
params:
  logo: ""
  favicon: "assets/favicon.png"

# Info
  address: "DM @wildfennmusic"
  email: "enquiries@wildfenn.co.uk"
  phone: "DM @wildfennmusic"

# Socials
  spotify: "https://open.spotify.com/artist/3BXB84OdyawXkx1wv5T6Ra?si=UUzIL9QkR1GiikFc3Yfdng"
  youtube: "https://www.youtube.com/@wildfenn"
  tiktok: "https://www.tiktok.com/@wildfenn"
  instagram: "https://www.instagram.com/wildfenn/"
  facebook: "https://www.facebook.com/wildfennmusic"
  bandcamp: "https://wildfenn.bandcamp.com/"
  github: "https://github.com/pillingworthz/wildfennmusic"

# Sign-up
  signup:
    enabled: false

# Startbootstrap Contact Form Token https://startbootstrap.com/solution/contact-forms
  sbtoken: "TOKEN_HERE"
